task: squad
train_path: datasets/squad/train-v2.0.json
dev_path: datasets/squad/dev-v2.0.json
preprocessed_data_path: datasets/preprocessed/preprocessed.pickle
embedding_path: embeddings/glove.6B.100d.txt
save_dir: saved_models/
num_iterations: 100000
hidden_size: 100
batch_size: 20
dev_batch_size: 100
dropout_keep_prob: 0.8
learning_rate: 0.001
maxout_pool_size: 4
decoding_iterations: 4
checkpoint: 2