task: marco
train_path: datasets/train_v2.1.json
dev_path: datasets/dev_v2.1.json
preprocessed_data_path: datasets/preprocessed/preprocessed.pickle
embedding_path: embeddings/glove.6B.100d.txt
num_iterations: 100
batch_size: 20